document.addEventListener("DOMContentLoaded", () => {
  const STORAGE_KEY_PROFILE = "fft_therapist_profile_v1";

  /* ---------------- ELEMENTS ---------------- */

  // Profile inputs
  const fields = [
    "therapistName",
    "therapistRole",
    "licenseNo",
    "experienceYears",
    "email",
    "phone",
    "clinicName",
    "clinicAddress",
    "timezone",
    "language",
    "privacyEmail",
    "defaultDisclaimer"
  ].map(id => document.getElementById(id));

  const fieldMap = Object.fromEntries(fields.map(el => [el.id, el]));

  // Assets
  const logoInput = document.getElementById("logoInput");
  const stampInput = document.getElementById("stampInput");
  const logoPreview = document.getElementById("logoPreview");
  const stampPreview = document.getElementById("stampPreview");

  // Buttons
  const editBtn = document.getElementById("editProfileBtn");
  const saveBtn = document.getElementById("saveProfileBtn");
  const cancelBtn = document.getElementById("cancelEditBtn");

  // Password
  const currentPassword = document.getElementById("currentPassword");
  const newPassword = document.getElementById("newPassword");
  const confirmPassword = document.getElementById("confirmPassword");
  const changePasswordBtn = document.getElementById("changePasswordBtn");

  // Plan view (READ-ONLY)
  const planNameView = document.getElementById("planNameView");
  const planStatusView = document.getElementById("planStatusView");
  const planPatientLimitView = document.getElementById("planPatientLimitView");
  const planAiView = document.getElementById("planAiView");
  const planExportsView = document.getElementById("planExportsView");
  const planSupportView = document.getElementById("planSupportView");

  const lastSavedText = document.getElementById("lastSavedText");

  /* ---------------- HELPERS ---------------- */

  function loadProfile() {
    return JSON.parse(localStorage.getItem(STORAGE_KEY_PROFILE) || "null");
  }

  function saveProfile(profile) {
    localStorage.setItem(STORAGE_KEY_PROFILE, JSON.stringify(profile));
  }

  function setEditMode(enabled) {
    fields.forEach(f => f.disabled = !enabled);
    logoInput.disabled = !enabled;
    stampInput.disabled = !enabled;

    saveBtn.disabled = !enabled;
    cancelBtn.disabled = !enabled;
  }

  function readFileAsDataURL(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }

  function setPreview(container, dataUrl) {
    container.innerHTML = dataUrl
      ? `<img src="${dataUrl}" alt="Uploaded">`
      : `<span class="placeholder">No image uploaded</span>`;
  }

  /* ---------------- INITIAL LOAD ---------------- */

  const defaults = {
    therapistName: "",
    therapistRole: "",
    licenseNo: "",
    experienceYears: "",
    email: "",
    phone: "",
    clinicName: "",
    clinicAddress: "",
    timezone: "Asia/Kolkata",
    language: "English",
    privacyEmail: "",
    defaultDisclaimer:
      "This output is generated by FFTPro as a clinical screening aid and must be interpreted by a qualified clinician.",
    logoDataUrl: "",
    stampDataUrl: "",
    plan: {
      name: "Starter",
      status: "Active",
      patientLimit: "250",
      ai: "Basic",
      exports: "PDF",
      support: "Email"
    },
    lastSavedAt: ""
  };

  const profile = loadProfile() || defaults;

  Object.keys(fieldMap).forEach(key => {
    fieldMap[key].value = profile[key] ?? "";
  });

  setPreview(logoPreview, profile.logoDataUrl);
  setPreview(stampPreview, profile.stampDataUrl);

  planNameView.textContent = profile.plan.name;
  planStatusView.textContent = profile.plan.status;
  planPatientLimitView.textContent = profile.plan.patientLimit;
  planAiView.textContent = profile.plan.ai;
  planExportsView.textContent = profile.plan.exports;
  planSupportView.textContent = profile.plan.support;

  lastSavedText.textContent = profile.lastSavedAt
    ? `Last saved: ${new Date(profile.lastSavedAt).toLocaleString()}`
    : "Not saved yet.";

  setEditMode(false);

  /* ---------------- EDIT MODE ---------------- */

  editBtn.addEventListener("click", () => {
    setEditMode(true);
  });

  cancelBtn.addEventListener("click", () => {
    if (!confirm("Discard unsaved changes?")) return;
    location.reload();
  });

  /* ---------------- SAVE PROFILE ---------------- */

  saveBtn.addEventListener("click", () => {
    const updated = {
      ...profile,
      ...Object.fromEntries(
        Object.entries(fieldMap).map(([k, el]) => [k, el.value.trim()])
      ),
      lastSavedAt: new Date().toISOString()
    };

    saveProfile(updated);
    lastSavedText.textContent = `Last saved: ${new Date(updated.lastSavedAt).toLocaleString()}`;
    alert("Profile updated successfully.");
    setEditMode(false);
  });

  /* ---------------- ASSET UPLOAD ---------------- */

  logoInput.addEventListener("change", async () => {
    const file = logoInput.files?.[0];
    if (!file) return;
    const dataUrl = await readFileAsDataURL(file);
    setPreview(logoPreview, dataUrl);

    const current = loadProfile() || {};
    current.logoDataUrl = dataUrl;
    saveProfile(current);
  });

  stampInput.addEventListener("change", async () => {
    const file = stampInput.files?.[0];
    if (!file) return;
    const dataUrl = await readFileAsDataURL(file);
    setPreview(stampPreview, dataUrl);

    const current = loadProfile() || {};
    current.stampDataUrl = dataUrl;
    saveProfile(current);
  });

  /* ---------------- CHANGE PASSWORD ---------------- */

  changePasswordBtn.addEventListener("click", () => {
    if (!currentPassword.value || !newPassword.value || !confirmPassword.value) {
      alert("Please fill all password fields.");
      return;
    }

    if (newPassword.value !== confirmPassword.value) {
      alert("New passwords do not match.");
      return;
    }

    alert("Password changed successfully. (Backend hookup pending)");
    currentPassword.value = "";
    newPassword.value = "";
    confirmPassword.value = "";
  });
});
