document.addEventListener("DOMContentLoaded", () => {
  const STORAGE_USERS = "fft_users_v1";
  const STORAGE_SESSION = "fft_session_v1";
  const STORAGE_PROFILE = "fft_therapist_profile_v1";

  const form = document.getElementById("registerForm");
  const errorBox = document.getElementById("errorBox");

  function loadUsers(){
    return JSON.parse(localStorage.getItem(STORAGE_USERS) || "[]");
  }
  function saveUsers(users){
    localStorage.setItem(STORAGE_USERS, JSON.stringify(users));
  }
  function setSession(email){
    localStorage.setItem(STORAGE_SESSION, JSON.stringify({
      email,
      createdAt: new Date().toISOString()
    }));
  }

  function validatePassword(pw){
    if (pw.length < 8) return "Password must be at least 8 characters.";
    if (!/\d/.test(pw)) return "Password should include at least 1 number.";
    return "";
  }

  // NOTE: This is demo-level hashing placeholder.
  // For production: hash on backend (bcrypt/argon2).
  function weakHash(str){
    let h = 0;
    for (let i=0;i<str.length;i++) h = (h<<5) - h + str.charCodeAt(i);
    return String(h >>> 0);
  }

  form.addEventListener("submit", (e) => {
    e.preventDefault();
    errorBox.textContent = "";

    const fullName = document.getElementById("fullName").value.trim();
    const email = document.getElementById("email").value.trim().toLowerCase();
    const phone = document.getElementById("phone").value.trim();
    const password = document.getElementById("password").value;
    const confirmPassword = document.getElementById("confirmPassword").value;
    const terms = document.getElementById("terms").checked;

    if (!terms) {
      errorBox.textContent = "Please accept the Terms & Privacy Policy.";
      return;
    }

    if (!fullName || !email || !password || !confirmPassword) {
      errorBox.textContent = "Please fill all required fields.";
      return;
    }

    const pwErr = validatePassword(password);
    if (pwErr) { errorBox.textContent = pwErr; return; }

    if (password !== confirmPassword) {
      errorBox.textContent = "Passwords do not match.";
      return;
    }

    const users = loadUsers();
    if (users.some(u => (u.email || "").toLowerCase() === email)) {
      errorBox.textContent = "An account with this email already exists. Please login.";
      return;
    }

    users.push({
      email,
      fullName,
      phone,
      passwordHash: weakHash(password),
      createdAt: new Date().toISOString(),
      resetToken: null
    });

    saveUsers(users);
    setSession(email);

    // Seed profile (optional but recommended)
    const profileSeed = {
      therapistName: fullName,
      therapistRole: "",
      licenseNo: "",
      experienceYears: null,
      email: email,
      phone: phone,
      clinicName: "",
      clinicAddress: "",
      timezone: "Asia/Kolkata",
      language: "English",
      privacyEmail: email,
      defaultDisclaimer: "This output is generated by FFTPro as a clinical screening aid and must be interpreted by a qualified clinician. It is not a standalone diagnosis.",
      logoDataUrl: "",
      stampDataUrl: "",
      plan: { name: "Starter", status: "Trial", renewalDate: "", billingCycle: "Monthly", notes: "Trial started on registration." },
      lastSavedAt: ""
    };
    localStorage.setItem(STORAGE_PROFILE, JSON.stringify(profileSeed));

    // Redirect to Profile (first-time setup)
    window.location.href = "profile.html";
  });
});
